import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import BootstrapActivation from "@/Helpers/BootstrapActivation";
import Header from "@/Components/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
	  <Header/>
	  <div className="container">
		  <main role="main" className="pb-3">
			  {children}
		  </main>
	  </div>
	  <BootstrapActivation />
      </body>
    </html>
  );
}
