"use client"

import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import BootstrapActivation from "@/Helpers/BootstrapActivation";
import Header from "@/Components/Header";
import {CartProvider} from "@/Context/CartContext";
import {AccountContext, IAccountInfo} from "@/Context/AccountContext";
import {useState} from "react";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	const [accountInfo, setAccountInfo] = useState<IAccountInfo | undefined>();

	const updateAccountInfo = (value: IAccountInfo) => {
		setAccountInfo(value);
		localStorage.setItem("_jwt", value.jwt!);
		localStorage.setItem("_refreshToken", value.refreshToken!);
	}

	return (
		<html lang="en">
		<body>
		  <AccountContext.Provider value={{
			  accountInfo: accountInfo,
			  setAccountInfo: updateAccountInfo,
		  }}>
			  <Header/>
			  <main className="flex-fill">
				  {children}
			  </main>
			  <BootstrapActivation />
		  </AccountContext.Provider>
		  </body>
		</html>
	  );
}
